name: Push to the docker branch and image build test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
 Docker-Ready-Repo:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Create annotation for build error
        run: |
              wget https://raw.githubusercontent.com/madhuryadutta/Hit-O-Meter/automation/docker/build_branch.sh 
              sudo chmod +x build_branch.sh
              ./build_branch.sh
              rm build_branch.sh
      
      # Other steps that change files in the repository

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Building Docker Ready repo

          # Optional. Local and remote branch name where commit is going to be pushed
          #  to. Defaults to the current branch.
          #  You might need to set `create_branch: true` if the branch does not exist.
          branch: docker

          # Optional. Options used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          # commit_options: "--no-verify --signoff"

          # Optional commit user and author settings
        # commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
        # commit_user_email: my-github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
        # commit_author: Author <actions@github.com> # defaults to "username <username@users.noreply.github.com>", where "username" belongs to the author of the commit that triggered the run

          # Optional. Tag name being created in the local repository and
          # pushed to remote repository and defined branch.
          tagging_message: "v1.0.0"

              # Optional. Options used by `git-push`.
          # See https://git-scm.com/docs/git-push#_options
          push_options: '--force'
    
          # Optional. Disable dirty check and always try to create a commit and push
          skip_dirty_check: true    
          
          # Optional. Create given branch name in local and remote repository.
          create_branch: true
          
      - name: Build the Docker image Test
        run: docker build . --file Dockerfile --tag hit-o-meter:$(date +%s)